


default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons" 
                                                                          
    firebase_app_distribution(
        app: "1:982127561430:android:ba69e0a2f6c59ac733d777",
        firebase_cli_token: ENV["FIERBASE_CLI_TOKEN"],
        # android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "aymanshawqi380@gmail.com",
        testers:"aymanshawki380@gmail.com",
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end



